import PageHeader from "@components/PageHeader.tsx";

import styles from "./Agreement.module.css";

export default function Agreement() {

    return (
        <div>
            <PageHeader>"Правила та умови використання"</PageHeader>
            <div className={styles.upperSegment}>
                <p> 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at tellus tincidunt, molestie nisl eu, dapibus dolor. Suspendisse consequat id neque et ultrices. Sed feugiat enim a sagittis semper. In sodales accumsan nunc, venenatis ultrices libero aliquam sed. Duis ac cursus ligula. Nam in vehicula odio. Nam id leo congue nibh mattis rutrum. Maecenas at ex eget arcu tempus varius et id elit. Fusce mollis eleifend est ut viverra. Mauris velit sapien, sagittis non imperdiet consectetur, eleifend eget est. </p>
                <p> 2. Nunc eget eros sollic    itudin, sodales leo facilisis, dapibus enim. Vivamus molestie consequat lectus, in ultrices sem dignissim vitae. Mauris vel rutrum ipsum. Vestibulum at risus non magna hendrerit tempor. Praesent aliquam diam et turpis accumsan consectetur. Praesent leo nisl, porttitor sit amet dolor non, euismod ullamcorper massa. Proin tincidunt interdum odio sed auctor. Fusce eu sagittis turpis, vel laoreet arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce non lobortis enim, ac pulvinar eros. Suspendisse interdum consectetur justo non tempus. Curabitur tristique mollis enim, ac dignissim quam egestas vitae. Etiam interdum dolor commodo arcu feugiat, eu dapibus tellus posuere. Vestibulum tempor turpis id sagittis volutpat. Donec tincidunt egestas nisl, at convallis ex varius et. In sit amet arcu a enim feugiat gravida ac a elit.</p>
                <p> 3. Quisque quis lacinia lectus. Donec sodales justo dui, vitae sagittis ligula malesuada id. Fusce nec pretium nisi. Nulla eu eros ante. Vivamus imperdiet nisl sit amet egestas ultrices. Cras dapibus, ligula et vestibulum bibendum, lorem nulla consequat elit, ut laoreet magna metus at libero. Aliquam dictum consectetur euismod. Vestibulum eget purus ac elit lacinia dapibus sit amet quis urna. Maecenas condimentum orci eget posuere ornare. Integer leo purus, aliquet vitae fringilla id, viverra nec dolor. Praesent sed ante imperdiet, congue nulla sit amet, rhoncus ex. Pellentesque ac ullamcorper libero. </p>
                <p> 4. Suspendisse mattis lacinia tellus, vel tempus nisl tristique eu. Sed sed urna consequat quam viverra venenatis malesuada a tellus. Sed ac finibus magna. Pellentesque non odio quis augue condimentum hendrerit sit amet vel leo. In mi nunc, lacinia vitae dui quis, sodales vulputate massa. Quisque facilisis auctor lectus, at tincidunt nisi vehicula sit amet. Donec luctus elit eget urna pellentesque, aliquet feugiat libero porttitor. Proin nulla dui, pretium sed posuere nec, mattis at turpis. Etiam in leo non nulla bibendum tempus ac at ex. Pellentesque at dolor ultrices, commodo quam non, consectetur ante. </p>
                <p> 5. Etiam eu sollicitudin metus. Duis aliquam bibendum enim ut aliquam. Cras finibus maximus leo, quis molestie mauris condimentum at. In tempus mauris eget ligula posuere, et bibendum felis malesuada. Nulla mattis nibh ipsum, vel fermentum est finibus eu. Praesent varius velit neque, vestibulum semper neque accumsan a. Duis vel luctus sapien. Aliquam aliquet mi vitae sapien interdum hendrerit. Aenean est neque, consequat quis ultrices vitae, condimentum quis libero. Maecenas et bibendum massa, non euismod leo. Pellentesque rutrum porttitor efficitur. Sed vitae nunc fringilla, aliquet ipsum at, fermentum dolor. Duis accumsan nisl enim, sed hendrerit nibh porta in. Nullam at turpis ultricies, consectetur arcu vel, elementum enim. Nullam a nisi magna. Duis sed pellentesque nulla. </p>
                <p> 6. Morbi cursus massa non leo ultricies volutpat. In hac habitasse platea dictumst. In ac quam augue. Phasellus id vestibulum purus, varius faucibus ligula. Etiam placerat, neque non efficitur suscipit, lacus elit congue felis, nec facilisis mauris velit non sapien. Duis eu libero risus. Phasellus ac feugiat tortor. Nam bibendum ipsum vel augue ornare feugiat. Cras bibendum nibh tempus, bibendum lorem quis, ultrices ex. Aenean non nibh pharetra, eleifend nunc ac, cursus turpis. Curabitur suscipit lacinia velit ac ullamcorper. Nulla condimentum sed neque ac sollicitudin. Praesent ac dolor purus. </p>
                <p> 7. Proin mollis elementum nulla, sed convallis massa aliquet ut. Integer blandit purus euismod turpis fermentum, nec accumsan urna consectetur. Aenean rhoncus vel urna eget vehicula. Sed cursus velit feugiat ex ultricies placerat. Ut tempor eu magna at volutpat. Aliquam a felis eget sem commodo dapibus sit amet sit amet ipsum. Mauris pulvinar lectus nisi, sit amet venenatis libero dignissim nec. Proin pharetra a turpis nec scelerisque. Nunc congue risus ut laoreet tincidunt. Integer in dolor ornare, hendrerit velit ac, pharetra nulla. Suspendisse potenti. Nunc facilisis sapien ac tellus dignissim, non congue sem finibus. </p>
                <p> 8. Donec posuere eleifend leo a tincidunt. Vestibulum malesuada, libero vel molestie malesuada, libero quam tincidunt ligula, eu vehicula risus purus non lorem. Curabitur diam risus, suscipit at pretium non, rutrum ac lectus. Vestibulum sed tortor elit. Morbi euismod ex sit amet vulputate tincidunt. Aenean bibendum ligula et leo suscipit, facilisis malesuada nulla dapibus. Integer tincidunt finibus nibh sed auctor. Quisque elementum leo ac blandit tempus. Proin pharetra sem lacus, id tincidunt mi pulvinar elementum. Morbi non lacinia dolor. Pellentesque lacinia tincidunt ex, in placerat metus fringilla in. Aliquam lectus nibh, auctor at laoreet vel, faucibus tempor diam. Donec egestas ultrices lectus. Morbi id accumsan augue. </p>
                <p> 9. Quisque vehicula pellentesque augue, in elementum mauris consequat nec. Donec porttitor tincidunt dolor, non feugiat lacus varius in. Curabitur in neque ornare, sagittis mi non, maximus massa. Morbi at accumsan neque, eget tempus purus. Vestibulum elit lacus, aliquam id convallis id, ultricies in mauris. Nam orci quam, vestibulum eget neque non, efficitur lobortis libero. Nunc lacinia dapibus convallis. Integer egestas elementum quam, eu efficitur dui. Quisque dignissim libero ligula, quis sollicitudin magna tempus quis. Nunc at ante lectus. Curabitur quis erat augue. </p>
                <p> 10. Suspendisse in turpis elit. Aliquam pretium lacinia sem, vitae porta felis convallis vitae. Morbi vel nulla velit. Vestibulum convallis arcu sit amet posuere commodo. Praesent molestie luctus imperdiet. Maecenas ac placerat neque. Pellentesque lectus erat, semper ut mauris ut, egestas euismod leo. Aliquam convallis egestas lorem a accumsan. Cras ut aliquam mi. Quisque iaculis eleifend turpis, sit amet malesuada mauris scelerisque vitae. Proin a libero eu ex mollis cursus id hendrerit ante. Morbi at nisl in nulla eleifend condimentum nec vitae ligula. Praesent feugiat ultricies tortor, a hendrerit nibh congue at. Donec at mollis lacus, imperdiet accumsan tortor. </p>
            </div>
            <div className={styles.lowerSegment}>
                <div className={styles.acceptContainer}>
                    <p> Я прочита(в/ла) умови користування та несу відповідальність за наслідки, що виникнуть у разі їх невиконання </p>              
                </div>
                <div className={styles.checkboxContainer}>
                    <input type="checkbox"/>
                </div>
            </div>
        </div>
    );
}