version: '3'

services:
  web_app:
    build: ./django-container
    volumes:
      - ./django-container:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./django-container/.env

  nginx_service:
    build: ./nginx-container
    ports:
      - 8080:80
    depends_on:
      - web_app
